### PR TITLE
Teach add to work with iterables

### PR DESCRIPTION
**Pull request by TalAmuyal**
Hi, @elimintz, thanks for this project!
I used JustPy in a hackathon a couple of weeks ago and I enjoy it very much :)

I'd like to suggest that `add` will support arguments that are iterables.
I find it useful when generating things in a comprehension.

For example:

```python
jp.Table().add(
    jp.Tr().add(
        ...
    ),
    [
        jp.Div(...)
        for user in users
    ],
)
```

What do you think?

### CODE REVIEW

**Comment by elimintz** [comment]
Hi Tal,

Thanks for using JustPy!

Please take a look at this example:

```python
import justpy as jp

def unpack_test():
    wp = jp.WebPage()
    d = jp.Div(a=wp)
    d.add(*[jp.Div(text=f'Start Div {i}', classes='m-2') for i in range(1,11)], jp.Div(text='Middle div'), 
          *[jp.Div(text=f'End Div {i}', classes='m-2') for i in range(1,11)])
    return wp


jp.justpy(unpack_test)
```

I may be missing something but I think you can get the functionality you are looking for using the * unpacking operator. Let me know what you think.

**Comment by TalAmuyal** [comment]
Indeed it will work, however I suggest adding support for the following version:

```py
import justpy as jp

def unpack_test():
    wp = jp.WebPage()
    d = jp.Div(a=wp)
    d.add([jp.Div(text=f'Start Div {i}', classes='m-2') for i in range(1,11)], jp.Div(text='Middle div'), 
          [jp.Div(text=f'End Div {i}', classes='m-2') for i in range(1,11)])
    return wp
```

This could be also nice when a function returns a list of Divs, for example:

```py
import justpy as jp

def unpack_test():
    wp = jp.WebPage()
    d = jp.Div(a=wp)
    d.add([jp.Div(text=f'Start Div {i}', classes='m-2') for i in range(1,11)], jp.Div(text='Middle div'), 
          make_bottom_part())
    return wp

def make_bottom_part():
    return [jp.Div(text=f'End Div {i}', classes='m-2') for i in range(1,11)]
```

If you don't want this feature, feel free to close this PR.

**Comment by TalAmuyal** [comment]
Another example:
```
def build_page(content):
    wp = jp.WebPage()
    d = jp.Div(a=wp)
    d.add(content)
    return wp
```

Where content could be a `jp.HTMLComponent` or a list of such.

**Comment by WolfgangFahl** [comment]
Wouldn't it be cleaner to have to different calls add_component and add_components?

**Comment by WolfgangFahl** [comment]
@TalAmuyal i would have merged this and modify it to show your collaboration. Since you are already on the collaborator list i feel that other issues and cleanups have priority and we might regret the decision to support this in the process of a general cleanup. I like the idea of being able to handle iterables but wouldn't force it with an instance of check but a separate function which we might readd later.

**Comment by TalAmuyal** [comment]
@WolfgangFahl , thanks for taking the time and investing in this project.
I'm fine with it either way.

**Pull request closed without merging**
