### PR TITLE
Fix a few broken links in docs/README.md

### PR DESCRIPTION
**Pull request by danlat**
Noticed the SVG and HTML links were broken on https://justpy.io/

### CODE REVIEW

**Comment by elimintz** [comment]
Thank you! I accept this commit. I won't actually merge it, but make the changes you suggest in the new version I am working on (I need to reconfigure my GitHub settings and am not an expert in this).

**Comment by danlat** [comment]
Great, thanks! Just curious, how different is the new version you're working on and do you have an ETA? I just recently discovered JustPy and wanted to make some more contributions in the near future, especially with the pandas to ag grid code

**Comment by elimintz** [comment]
> Great, thanks! Just curious, how different is the new version you're working on and do you have an ETA? I just recently discovered JustPy and wanted to make some more contributions in the near future, especially with the pandas to ag grid code

There are no breaking changes in the new version and there are no changes to pandas and ag-grid code. It is mostly bug fixes. ETA is sometime in January. I'd be happy to discuss your ideas on https://github.com/elimintz/justpy/discussions

**Comment by WolfgangFahl** [comment]
you might want to close this PR

**Pull request closed without merging**
