### PR TITLE
Add QInput min/max properties (for type='number')

### PR DESCRIPTION
**Pull request by eudoxos**
See https://codepen.io/smolinari/pen/XWroYBq?editors=1010 for an example

### CODE REVIEW

**Comment by elimintz** [comment]
This is a simple change that requires adding 'min' and 'max' to the default prop_list of QInput. It will be part of the new version.

For now, you can do so explicitly like this:
```python
import justpy as jp


def input_example():
    wp = jp.QuasarPage()
    my_input = jp.QInput(type='number', label="Enter a Number", filled=True, a=wp, style='width: 300px', min=1, max=10)
    my_input.prop_list.extend(['min', 'max'])
    return wp

jp.justpy(input_example)
```

**Comment by eudoxos** [comment]
> This is a simple change that requires adding 'min' and 'max' to the default prop_list of QInput.
That's the contents of the PR :)

**Comment by elimintz** [comment]
Sorry, I am new to working with PRs.... In any case I made this change.

**Comment by eudoxos** [comment]
No problem, we all learn. Next time, you can just review the PR commit and merge (or comment in the code of the commit). We can try with the logging again. Thanks for JustPy. :)

**Pull request closed without merging**
