### PR TITLE
GIFs / Images in README & Documentation

### PR DESCRIPTION
**Pull request by JackMcKew**
Hi!

I found out about this project from [Python Bytes](https://pythonbytes.fm/), and thought the documentation & readme was missing the visual part.

I've done a few sections with adding GIFs and static images, still yet to complete them all (the documentation is very extensive).

Just let me know if you want me to keep going for the rest of them or if there is a more automated way of doing this.

P.S. Unsure about the documentation CI/CD and it's ability to handle images, let me know if there's anyway I can fix that for you

### CODE REVIEW

**Comment by elimintz** [comment]
Thank you, will review tomorrow. Which episode pf Python Bytes mentioned JustPy?

**Comment by JackMcKew** [comment]
Episode 170

https://pythonbytes.fm/episodes/show/170/visualize-this-visualizing-python-s-visualization-ecosystem

Regards,

Jack McKew

Consultant | Cyberlytica

Phone: 0431 670 387
ABN: 2073 2126 434

**Comment by elimintz** [comment]
Thanks again for the gifs. 

My current thinking is that the examples in the tutorial are simple to run and therefore you don't need the gifs. One of the goals of the tutorial is to get people to actually use the framework and I envision people making small changes in the examples to see how the results look like.

If you decide to make a repository with the images, I would be happy to describe and link to it from the tutorial so that people who do want images can take a look.

**Comment by JackMcKew** [comment]
In my opinion, I don't see how providing prospective users a snapshot of what this package could be used for with a quick glance is detrimental in any way.  For a prospective user to go to the effort of setting up Python + Virtual Envs + Dependencies just to even see if they like it is not favourable. Especially for a more visual-based package such as this.

As a prospective user of a package, personally, I'd appreciate if I can just look up the repositories README and have an image/video of what this package could do for me.

My personal favourite README of any python package that I have come across, is that of, [Pandas-Bokeh](https://github.com/PatrikHlobil/Pandas-Bokeh). As a user, I can jump on, without programming at all and see what this package could do for me.

**Pull request closed without merging**
