### PR TITLE
Use separate logger for JustPy (name and level customizable)

### PR DESCRIPTION
**Pull request by eudoxos**
Add `JustPy.log` logger with `LOGGING_LOGGER` name (`JustPy` by default) and `LOGGING_LEVEL` level, both may be set in `justpy.env`. (no clue how the min/max branch got in here... :/ )

### CODE REVIEW

**Comment by elimintz** [comment]
Excellent, thank you very much! I accept these changes and they will be in the next version. I have not merged the pull request because I am not a git expert and am having issues syncing my local repositories and the one on GitHub.

**Comment by cheak1974** [comment]
Hi,
would be great if one could configure the location of a log file but also the complete formatting.

Maybe it would be a good idea to add a jp.get_logger(name=None) method along with a jp.custom_log_handler(handler).

So everybody could leave it alone or just change the location of the log file via justpy.env or use it just with a customer handler.

```python

def get_my_file_handler():
    formatter = logging.Formatter('{asctime}|{levelname:8}|{name:50}|{filename:30}|{funcName:30}|{lineno:6}|{message}', datefmt='%Y-%m-%dT%H:%M:%S', style='{')
    file_handler = logging.FileHandler(sys.path[0] + '/log/mylogfile.log')
    file_handler.setLevel(logging.ERROR)        # Logging Level for file logging
    file_handler.setFormatter(formatter)
    return file_handler

# Completely custom logging
jp.custom_log_handler(get_my_file_handler())
logger = jp.get_logger(__name__)

```

Maybe an idea to take into account.

regards

Chris

**Comment by eudoxos** [comment]
I don't see a need for `jp.get_logger`: standard `logging.getLogger('justpy')` gets the justpy (internal) logger object from anywhere, along with the ability to set handlers, formatting etc.

**Comment by cheak1974** [comment]
You are right. If justpy is just taking the standard logger then the entire issue/pull is somehow obsolete at all.

**Comment by WolfgangFahl** [comment]
please close this if it's not used any more and invite more people so that the project can make progress.

**Pull request closed without merging**
