### PR TITLE
QEditor: add `placeholder` to list of properties

### PR DESCRIPTION
**Pull request by Bystroushaak**
Added `placeholder` to the list of QEditor's properties & fixed typo in doc.

### CODE REVIEW

**Comment by elimintz** [comment]
Thank you! I I made the changes and they will be available in next version. (The code base I work on is not in github, just the latest version)

**Comment by Bystroushaak** [comment]
Thanks.

**Comment by Bystroushaak** [comment]
If you allow me a question, why don't you work more with github? With git, you can merge the changes here on github using pull requests to `master` branch (or devel branch, whatever), then download changelist to your computer, and merge/cherrypick changes from the master to your dev branch, on which you are basing your new release.

**Comment by Bystroushaak** [comment]
Hm. I've looked into the git history, and it seems to me that you are using git .. weirdly. Are you using something else for source code management?

**Comment by elimintz** [comment]
I am using git from within the Pycharm environment but probably have the configuration wrong because in the past when I accepted changes on Github it messed up my local files so now I use it just in one direction. I need to find the time to get this in order.

**Comment by Bystroushaak** [comment]
I am also using the PyCharm. I think it really depends on how are you using git in general.

Typically I use it in "pseudo [git flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)" way. That is to have release version as a `master` branch, do my own custom development on different branch, where I commit a lot (-> no uncommited changes there). I can still accept changes into the master from other people in form of pull requests (which I merge on github and pull from github on my computer), and then merge `master` or `cherrypick` branch back to my development branch.

When I want to do a release, I do a merge of my development branch to the master, and tag it as a release (in PyCharm, you can just right click on the commit in git and select _add tag_).

I don't want to sound condescending, it just feels to me that you are doing a lot of unnecessary work. I really love your project, and can't thank you enough for it. I just think that if you work with commits and move them using git, it's much simpler than moving changes like you described you are doing.

**Comment by elimintz** [comment]
You are right. I am not using git as it is supposed to be used and wasting time. Unfortunately, I never had the chance to use git at work so really have no experience with it. I'll figure this out soon I hope.

**Pull request closed without merging**
